<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Akash" failures="1" tests="2" name="Test(failed)" time="18.796" errors="0" timestamp="2024-09-21T15:11:39 IST">
  <testcase classname="task.BrokenLinks" name="BrokenLinkTest" time="4.6">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Link: &amp;apos;Appium&amp;apos; is broken with status code 403 expected [true] but found [false],
	Link: &amp;apos;Broken Link&amp;apos; is broken with status code 404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Link: 'Appium' is broken with status code 403 expected [true] but found [false],
Link: 'Broken Link' is broken with status code 404 expected [true] but found [false]
at task.BrokenLinks.BrokenLinkTest(BrokenLinks.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- BrokenLinkTest -->
  <testcase classname="practiceSelenium.LoginBaseClass" name="UrlValidateTest" time="0.036"/>
  <testcase classname="practiceSelenium.LoginBaseClass" name="testLogin" time="0.0">
    <ignored/>
  </testcase> <!-- testLogin -->
</testsuite> <!-- Test(failed) -->
